export const COMMON_AMENITIES = [
  "WiFi",
  "Parkering",
  "Kjøkken",
  "Oppvaskmaskin",
  "Kjøleskap",
  "Fryser",
  "Stekeovn",
  "Mikrobølgeovn",
  "Kaffemaskin",
  "Vannkoker",
  "Peis",
  "Badstue",
  "Badehus",
  "Boblebad",
  "TV",
  "Kabel-TV",
  "Vaskemaskin",
  "Tørketrommel",
  "Ski-in/ski-out",
  "Skotørker",
  "Sengetøy",
  "Håndklær",
  "Grill",
  "Balkong",
  "Terrasse",
  "Uteplass",
  "Barnevennlig",
  "Kjæledyr tillatt",
  "Røyking forbudt",
  "Tilgjengelig for rullestol",
];
