"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_OPTIONS = ["no", "en", "fr", "es", "it"];

const dictionaries = {
  no: {
    footer: {
      text: "Fritt Fram. Planlegg turer, hytter og opplevelser på tvers av hele appen.",
    },
    topBar: {
      search: "Søk",
      explore: "Utforsk",
      reserve: "Reserver",
      map: "Kart",
      weather: "Vær",
      social: "Sosial",
      navigate: "Naviger",
      home: "Hjem",
      menu: "Meny",
      currentPage: "Aktiv side",
      quickActions: "Hurtigvalg",
      language: "Språk",
      profile: "Profil",
      settings: "Innstillinger",
      login: "Logg inn",
      logout: "Logg ut",
      guest: "Ikke innlogget",
      signedInAs: "Innlogget som",
      account: "Konto",
      ads: "Marked",
      adPortal: "Annonseportal",
    },
    home: {
      title: "Fritt Fram",
      subtitle: "Oppdag nye stier, pust inn fjelluften og finn ditt neste eventyr",
      searchPlaceholder: "Søk etter tur, sted eller aktivitet...",
      noResults: "Ingen resultater",
      todaysTrip: "Dagens tur",
      popularRoutes: "Populære turer",
      cabinSuggestions: "Hytteforslag",
      start: "Start",
      weather: "Vær",
      explore: "Utforsk",
      map: "Kart",
      social: "Sosial",
      reserve: "Reserver",
      searchBtn: "Søk",
      showAllResults: "Se alle treff",
      carouselEyebrow: "Populært nå",
      carouselTitle: "Utforsk det beste",
      tagLabels: { cabin: "Hytte", hike: "Fottur", market: "Marked", rorbu: "Rorbu", bike: "Sykkel", forum: "Forum", weather: "Vær", climb: "Klatring" },
      cards: [
        { label: "Overnatting", title: "Fjellhytte i Jotunheimen", desc: "Rustikk hytte med utsikt over Besseggen. Plass til 8.", cta: "Reserver nå" },
        { label: "Aktivitet", title: "Langtur på Hardangervidda", desc: "5-dagersrute gjennom ett av Europas største høyfjellsplatåer.", cta: "Se ruten" },
        { label: "Utstyr", title: "Fjellsko til alle terreng", desc: "Testet og godkjent av norske turfolk. Nå i Marked.", cta: "Se tilbud" },
        { label: "Overnatting", title: "Kystferie på Lofoten", desc: "Rorbu rett ved sjøen. Sol, sjømat og midnattssol.", cta: "Reserver nå" },
        { label: "Aktivitet", title: "Sykkeltur langs Rallarvegen", desc: "82 km over fjellet – Norges kuleste sykkelrute.", cta: "Se ruten" },
        { label: "Fellesskap", title: "Del din neste tur", desc: "Finn turkamerater og del opplevelser i forumet.", cta: "Gå til forum" },
        { label: "Vær", title: "Sjekk værvarselet", desc: "Oppdatert fjellvær for over 500 norske topper.", cta: "Åpne kart" },
        { label: "Aktivitet", title: "Toppturer i Romsdalen", desc: "Klassiske ruter med spektakulær utsikt. Alle nivåer.", cta: "Utforsk" },
        { label: "Overnatting", title: "Sommerhytte ved innsjø", desc: "Stillhet, padling og fiske. Booking åpent for sommer.", cta: "Reserver nå" },
      ],
    },
    searchPage: {
      eyebrow: "Globalt søk",
      title: "Finn turer og hytter",
      subtitle: "Søk etter turer, steder og hytter. Resultatene leder videre til utforsk- og reservasjonsvisningene.",
      inputPlaceholder: "Søk etter tur eller hytte",
      submit: "Søk",
      suggestions: "Forslag",
      searchTerm: "Søkeord",
      trips: "Turer",
      cabins: "Hytter",
      totalResults: "Treff totalt",
      loading: "Søker i turer og hytter...",
      noHitsTitle: "Ingen treff",
      noHitsDescription: "Prøv et annet søkeord, eller gå direkte til utforsk- og reservasjonssidene.",
      noDescription: "Ingen beskrivelse tilgjengelig.",
      openExplore: "Se i utforsk",
      openReserve: "Se i reservasjon",
    },
    explorePage: {
      title: "Utforsk Norge",
      subtitle: "Finn turer over hele landet",
      createTrip: "Opprett tur",
      searchPlaceholder: "Søk etter tur",
      allTypes: "Alle typer",
      hike: "Fottur",
      ski: "Skitur",
      bike: "Sykkel",
      difficulty: "Vanskelighet",
      easy: "Lett",
      medium: "Middels",
      hard: "Krevende",
      tiuOnly: "Kun TiU-fellesturer",
      trips: "Turer",
      noTrips: "Ingen turer funnet",
      createTitle: "Opprett ny tur",
      close: "Lukk",
      openDetails: "Se detaljer",
      name: "Navn",
      description: "Beskrivelse",
      imageUrl: "Bilde-URL",
      length: "Lengde (km)",
      type: "Type",
      difficultyLabel: "Vanskelighetsgrad",
      startLat: "Start lat",
      startLng: "Start lng",
      endLat: "Slutt lat",
      endLng: "Slutt lng",
      tiuToggle: "Dette er en TiU-fellestur",
      leader: "Turleder",
      submit: "Lagre tur",
      submitError: "Kunne ikke opprette tur",
      fetchError: "Kunne ikke hente turer",
      genericError: "Noe gikk galt",
    },
    reservePage: {
      loadingCabins: "Laster hytter...",
      availableCabins: "Hytter tilgjengelig: {count} funnet",
      selectCabin: "Velg en hytte",
      noCabins: "Ingen hytter i databasen enda.",
      location: "Sted",
      capacity: "Kapasitet",
      people: "personer",
      pricePerNight: "kr per natt",
      noAmenities: "Ingen registrerte fasiliteter",
      reserveCabin: "Reserver denne hytta",
      addCabin: "Legg til ny hytte",
      loading: "Laster...",
      loadError: "Kunne ikke laste data.",
      selectPrompt: "Velg en hytte i listen for å se detaljer.",
      cabinsLoadError: "Kunne ikke hente hytter fra databasen.",
      unknownCabinError: "Ukjent feil ved henting av hytter.",
    },
    newCabinPage: {
      notice: "Legg til ny hytte",
      noticeDetail: "lagres i databasen",
      tips: "Tips",
      facilityTip: "Fasiliteter: skriv kommaseparert",
      priceTip: "Pris og kapasitet må være tall",
      locationTip: "Lokasjon er f.eks: Hemsedal, Norge",
      backOverview: "Tilbake til oversikt",
      newCabin: "Ny hytte",
      pinRequired: "Du må plassere en pin på kartet for hyttens posisjon.",
      saving: "Lagrer...",
      saveCabin: "Lagre hytte",
      savedCabin: "Hytta ble lagret: {name}",
      saveError: "Kunne ikke lagre hytta.",
      networkError: "Nettverksfeil / serverfeil.",
      namePlaceholder: "Navn (påkrevd)",
      descriptionPlaceholder: "Beskrivelse (valgfri)",
      locationPlaceholder: "Lokasjon (påkrevd)",
      pricePlaceholder: "Pris per natt (kr)",
      capacityPlaceholder: "Kapasitet (antall personer)",
      amenitiesPlaceholder: "Fasiliteter (kommaseparert)",
      mapLabel: "Velg plassering på kartet",
      mapHelp: "Klikk på kartet for å plassere en pin. Koordinatene lagres sammen med hytta.",
      selectedPosition: "Valgt posisjon: {lat}, {lon}",
      overview: "Til oversikt",
    },
    messagesPage: {
      title: "Meldinger",
      loading: "Laster...",
      selectUser: "Velg bruker å chatte med:",
      choose: "Velg",
      loadingUsers: "Laster brukere...",
      loadingMessages: "Laster meldinger...",
      noMessages: "Ingen meldinger ennå. Skriv den første!",
      inputPlaceholder: "Skriv en melding...",
      send: "Send",
      currentUserError: "Kunne ikke hente innlogget bruker",
      usersError: "Kunne ikke hente brukere",
      messagesError: "Kunne ikke hente meldinger",
      sendError: "Kunne ikke sende melding",
    },
    weatherPage: {
      title: "Værsøk",
      inputPlaceholder: "Søk etter sted",
      submit: "Søk",
      now: "Nå",
      temperature: "Temperatur",
      wind: "Vind",
      humidity: "Fuktighet",
      precipitation: "Nedbør (1t)",
      forecast: "7-dagers prognose",
      noResults: "Ingen steder funnet.",
    },
    mapPage: {
      title: "Kart over Norge",
    },
    utforskPage: {
      title: "Utforsk",
      description: "Her kan du utforske spennende steder og opplevelser.",
    },
    settingsPage: {
      title: "Innstillinger",
      description: "Endre innstillinger her.",
    },
    loginPage: {
      eyebrow: "Innlogging",
      title: "Logg inn igjen",
      subtitle: "Etter utlogging må du logge inn på nytt for å få tilgang til profil, meldinger og andre beskyttede sider.",
      checking: "Sjekker innloggingsstatus...",
      email: "E-post",
      password: "Passord",
      forgotPassword: "Glemt passord?",
      forgotPasswordHelp: "Skriv inn e-post og nytt passord for å overskrive det gamle passordet i databasen.",
      newPassword: "Nytt passord",
      confirmNewPassword: "Bekreft nytt passord",
      resetPassword: "Oppdater passord",
      resettingPassword: "Oppdaterer passord...",
      resetSuccess: "Passordet er oppdatert. Det gamle passordet virker ikke lenger.",
      resetError: "Kunne ikke oppdatere passordet",
      passwordMismatch: "Passordene må være like",
      passwordTooShort: "Passordet må være minst 8 tegn",
      submitting: "Logger inn...",
      submit: "Logg inn",
      noAccount: "Har du ikke konto?",
      signUp: "Registrer deg",
      loginError: "Kunne ikke logge inn",
    },
    signupPage: {
      title: "Registrer deg",
      username: "Brukernavn",
      email: "E-post",
      password: "Passord (minst 8 tegn)",
      confirmPassword: "Bekreft passord",
      landlordSignupLabel: "Jeg registrerer meg som utleier",
      landlordSignupHint: "Du blir registrert med rollen Utleier.",
      tourGuideSignupLabel: "Jeg registrerer meg som turleder",
      tourGuideSignupHint: "Du blir registrert med rollen Turleder.",
      userSignupHint: "Hvis du ikke krysser av, registreres du som vanlig bruker.",
      submitting: "Oppretter konto...",
      submit: "Opprett konto",
      signupError: "Kunne ikke opprette konto",
      genericError: "Noe gikk galt",
    },
    socialPage: {
      title: "Sosial",
      captionPlaceholder: "Skriv et innlegg",
      publish: "Publiser",
      likes: "liker",
      currentUserError: "Kunne ikke hente innlogget bruker",
      publishError: "Kunne ikke publisere innlegg",
      likeError: "Kunne ikke oppdatere likerstatus",
      shareCopied: "Lenke kopiert",
    },
    profilePage: {
      loading: "Laster profil fra API...",
      account: "Min konto",
      transactions: "Transaksjoner",
      reservations: "Reservasjoner",
      reservationsIntro: "Her ser du hyttene du har booket.",
      wishlist: "Ønskeliste",
      wishlistIntro: "Her ser du hyttene du har lagret som favoritter.",
      loadingWishlist: "Laster ønskeliste...",
      noWishlistCabins: "Du har ingen hytter på ønskelisten ennå.",
      removeFromWishlist: "Fjern fra ønskeliste",
      removingFromWishlist: "Fjerner...",
      loadingReservations: "Laster reservasjoner...",
      noReservations: "Du har ingen registrerte reservasjoner ennå.",
      noCabinImage: "Ingen bilde",
      cabinFallback: "Hytte",
      locationUnavailable: "Lokasjon ikke tilgjengelig",
      pricePerNight: "Pris per natt",
      capacity: "Kapasitet",
      people: "personer",
      from: "Fra",
      to: "Til",
      guests: "Personer",
      openCabin: "Åpne hytte",
      statusCancelled: "Kansellert",
      statusConfirmed: "Bekreftet",
      statusPending: "Venter",
      statusActive: "Aktiv",
      payment: "Betaling",
      trips: "Turer",
      settings: "Innstillinger",
      logout: "Logg ut",
      categories: "Kategorier",
      changeImage: "Bytt bilde",
      editProfile: "Rediger profil",
      name: "Navn",
      birthDate: "Fødselsdato",
      age: "Alder",
      phone: "Telefon",
      email: "E-post",
      bio: "Bio",
      save: "Lagre",
      cancel: "Avbryt",
      details: "Detaljer",
      date: "Dato",
      distance: "Distanse",
      duration: "Varighet",
      elevation: "Stigning",
      rating: "Vurdering",
      viewPhotos: "Se alle bildene fra turen",
      paymentInfo: "Betalingsinformasjon",
      billingInfo: "Faktureringsinformasjon",
      billingDate: "Faktureringsdato",
      myTrips: "Mine turer",
      viewMap: "Se på kart",
      notifications: "Varslinger",
      notificationsHelp: "Motta varsler om nye meldinger og reservasjoner",
      theme: "Tema",
      themeHelp: "Velg farge- og designpreferanser",
      chooseTheme: "Velg tema",
      lightTheme: "Lyst tema",
      darkTheme: "Mørkt tema",
      autoTheme: "Automatisk",
      done: "Ferdig",
      confirmLogout: "Er du sikker?",
      place: "Sted",
    },
  },
  en: {
    footer: {
      text: "Fritt Fram. Plan trips, cabins and experiences across the entire app.",
    },
    topBar: {
      search: "Search",
      explore: "Explore",
      reserve: "Reserve",
      map: "Map",
      weather: "Weather",
      social: "Social",
      navigate: "Navigate",
      home: "Home",
      menu: "Menu",
      currentPage: "Current page",
      quickActions: "Quick actions",
      language: "Language",
      profile: "Profile",
      settings: "Settings",
      login: "Sign in",
      logout: "Sign out",
      guest: "Not signed in",
      signedInAs: "Signed in as",
      account: "Account",
      ads: "Marked",
      adPortal: "Ad Portal",
    },
    home: {
      title: "Fritt Fram",
      subtitle: "Discover new trails, breathe the mountain air and find your next adventure",
      searchPlaceholder: "Search for a trip, place or activity...",
      noResults: "No results",
      todaysTrip: "Today's trip",
      popularRoutes: "Popular routes",
      cabinSuggestions: "Cabin suggestions",
      start: "Start",
      weather: "Weather",
      explore: "Explore",
      map: "Map",
      social: "Social",
      reserve: "Reserve",
      searchBtn: "Search",
      showAllResults: "Show all results",
      carouselEyebrow: "Popular now",
      carouselTitle: "Explore the best",
      tagLabels: { cabin: "Cabin", hike: "Hiking", market: "Market", rorbu: "Fisherman's cabin", bike: "Cycling", forum: "Community", weather: "Weather", climb: "Climbing" },
      cards: [
        { label: "Accommodation", title: "Mountain cabin in Jotunheimen", desc: "Rustic cabin with views of Besseggen. Sleeps 8.", cta: "Book now" },
        { label: "Activity", title: "Long hike on Hardangervidda", desc: "5-day route through one of Europe's largest mountain plateaus.", cta: "See route" },
        { label: "Gear", title: "Mountain boots for all terrain", desc: "Tested and approved by Norwegian hikers. Now in the Market.", cta: "See offer" },
        { label: "Accommodation", title: "Coastal stay in Lofoten", desc: "Fisherman's cabin by the sea. Sun, seafood and midnight sun.", cta: "Book now" },
        { label: "Activity", title: "Cycling along Rallarvegen", desc: "82 km over the mountain – Norway's finest cycling route.", cta: "See route" },
        { label: "Community", title: "Share your next trip", desc: "Find hiking partners and share experiences in the forum.", cta: "Go to forum" },
        { label: "Weather", title: "Check the forecast", desc: "Updated mountain weather for over 500 Norwegian peaks.", cta: "Open map" },
        { label: "Activity", title: "Summit tours in Romsdalen", desc: "Classic routes with spectacular views. All levels.", cta: "Explore" },
        { label: "Accommodation", title: "Summer cabin by the lake", desc: "Peace, paddling and fishing. Booking open for summer.", cta: "Book now" },
      ],
    },
    searchPage: {
      eyebrow: "Global search",
      title: "Find trips and cabins",
      subtitle: "Search for trips, places and cabins. The results link directly into the explore and booking views.",
      inputPlaceholder: "Search for a trip or cabin",
      submit: "Search",
      suggestions: "Suggestions",
      searchTerm: "Search term",
      trips: "Trips",
      cabins: "Cabins",
      totalResults: "Total results",
      loading: "Searching trips and cabins...",
      noHitsTitle: "No results",
      noHitsDescription: "Try another search term, or go directly to the explore and booking pages.",
      noDescription: "No description available.",
      openExplore: "Open in explore",
      openReserve: "Open in booking",
    },
    explorePage: {
      title: "Explore Norway",
      subtitle: "Find trips across the country",
      createTrip: "Create trip",
      searchPlaceholder: "Search trips",
      allTypes: "All types",
      hike: "Hike",
      ski: "Ski",
      bike: "Bike",
      difficulty: "Difficulty",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      tiuOnly: "Only TiU group trips",
      trips: "Trips",
      noTrips: "No trips found",
      createTitle: "Create new trip",
      close: "Close",
      openDetails: "View details",
      name: "Name",
      description: "Description",
      imageUrl: "Image URL",
      length: "Length (km)",
      type: "Type",
      difficultyLabel: "Difficulty",
      startLat: "Start lat",
      startLng: "Start lng",
      endLat: "End lat",
      endLng: "End lng",
      tiuToggle: "This is a TiU group trip",
      leader: "Trip leader",
      submit: "Save trip",
      submitError: "Could not create trip",
      fetchError: "Could not fetch trips",
      genericError: "Something went wrong",
    },
    reservePage: {
      loadingCabins: "Loading cabins...",
      availableCabins: "Cabins available: {count} found",
      selectCabin: "Choose a cabin",
      noCabins: "No cabins in the database yet.",
      location: "Location",
      capacity: "Capacity",
      people: "people",
      pricePerNight: "per night",
      noAmenities: "No registered amenities",
      reserveCabin: "Reserve this cabin",
      addCabin: "Add new cabin",
      loading: "Loading...",
      loadError: "Could not load data.",
      selectPrompt: "Choose a cabin from the list to view details.",
      cabinsLoadError: "Could not fetch cabins from the database.",
      unknownCabinError: "Unknown error while loading cabins.",
    },
    newCabinPage: {
      notice: "Add new cabin",
      noticeDetail: "saved to the database",
      tips: "Tips",
      facilityTip: "Amenities: write them comma separated",
      priceTip: "Price and capacity must be numbers",
      locationTip: "Location can be for example: Hemsedal, Norway",
      backOverview: "Back to overview",
      newCabin: "New cabin",
      pinRequired: "You must place a pin on the map for the cabin position.",
      saving: "Saving...",
      saveCabin: "Save cabin",
      savedCabin: "Cabin saved: {name}",
      saveError: "Could not save the cabin.",
      networkError: "Network or server error.",
      namePlaceholder: "Name (required)",
      descriptionPlaceholder: "Description (optional)",
      locationPlaceholder: "Location (required)",
      pricePlaceholder: "Price per night",
      capacityPlaceholder: "Capacity (number of people)",
      amenitiesPlaceholder: "Amenities (comma separated)",
      mapLabel: "Choose a location on the map",
      mapHelp: "Click on the map to place a pin. The coordinates are saved with the cabin.",
      selectedPosition: "Selected position: {lat}, {lon}",
      overview: "To overview",
    },
    messagesPage: {
      title: "Messages",
      loading: "Loading...",
      selectUser: "Choose a user to chat with:",
      choose: "Choose",
      loadingUsers: "Loading users...",
      loadingMessages: "Loading messages...",
      noMessages: "No messages yet. Send the first one.",
      inputPlaceholder: "Write a message...",
      send: "Send",
      currentUserError: "Could not fetch the logged in user",
      usersError: "Could not fetch users",
      messagesError: "Could not fetch messages",
      sendError: "Could not send message",
    },
    weatherPage: {
      title: "Weather search",
      inputPlaceholder: "Search for a place",
      submit: "Search",
      now: "Now",
      temperature: "Temperature",
      wind: "Wind",
      humidity: "Humidity",
      precipitation: "Precipitation (1h)",
      forecast: "7-day forecast",
      noResults: "No places found.",
    },
    mapPage: {
      title: "Map of Norway",
    },
    utforskPage: {
      title: "Explore",
      description: "Explore places and experiences here.",
    },
    settingsPage: {
      title: "Settings",
      description: "Change your settings here.",
    },
    loginPage: {
      eyebrow: "Sign in",
      title: "Sign in again",
      subtitle: "After signing out, you need to sign in again to access profile, messages and other protected pages.",
      checking: "Checking sign-in status...",
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot password?",
      forgotPasswordHelp: "Enter your email and a new password to overwrite the old password in the database.",
      newPassword: "New password",
      confirmNewPassword: "Confirm new password",
      resetPassword: "Update password",
      resettingPassword: "Updating password...",
      resetSuccess: "Password updated. The old password no longer works.",
      resetError: "Could not update the password",
      passwordMismatch: "Passwords must match",
      passwordTooShort: "Password must be at least 8 characters",
      submitting: "Signing in...",
      submit: "Sign in",
      noAccount: "Don't have an account?",
      signUp: "Create one",
      loginError: "Could not sign in",
    },
    signupPage: {
      title: "Create account",
      username: "Username",
      email: "Email",
      password: "Password (minimum 8 characters)",
      confirmPassword: "Confirm password",
      landlordSignupLabel: "I am signing up as a landlord",
      landlordSignupHint: "You will be registered with the Landlord role.",
      tourGuideSignupLabel: "I am signing up as a tour guide",
      tourGuideSignupHint: "You will be registered with the Tour Guide role.",
      userSignupHint: "If you leave this unchecked, you will be registered as a regular user.",
      submitting: "Creating account...",
      submit: "Create account",
      signupError: "Could not create account",
      genericError: "Something went wrong",
    },
    socialPage: {
      title: "Social",
      captionPlaceholder: "Write a post",
      publish: "Publish",
      likes: "likes",
      currentUserError: "Could not fetch the logged in user",
      publishError: "Could not publish post",
      likeError: "Could not update like status",
      shareCopied: "Link copied",
    },
    profilePage: {
      loading: "Loading profile from API...",
      account: "My account",
      transactions: "Transactions",
      reservations: "Reservations",
      reservationsIntro: "Here you can see the cabins you have booked.",
      wishlist: "Wishlist",
      wishlistIntro: "Here you can see the cabins you have saved as favorites.",
      loadingWishlist: "Loading wishlist...",
      noWishlistCabins: "You have no cabins in your wishlist yet.",
      removeFromWishlist: "Remove from wishlist",
      removingFromWishlist: "Removing...",
      loadingReservations: "Loading reservations...",
      noReservations: "You have no registered reservations yet.",
      noCabinImage: "No image",
      cabinFallback: "Cabin",
      locationUnavailable: "Location unavailable",
      pricePerNight: "Price per night",
      capacity: "Capacity",
      people: "people",
      from: "From",
      to: "To",
      guests: "Guests",
      openCabin: "Open cabin",
      statusCancelled: "Cancelled",
      statusConfirmed: "Confirmed",
      statusPending: "Pending",
      statusActive: "Active",
      payment: "Payment",
      trips: "Trips",
      settings: "Settings",
      logout: "Sign out",
      categories: "Categories",
      changeImage: "Change image",
      editProfile: "Edit profile",
      name: "Name",
      birthDate: "Birth date",
      age: "Age",
      phone: "Phone",
      email: "Email",
      bio: "Bio",
      save: "Save",
      cancel: "Cancel",
      details: "Details",
      date: "Date",
      distance: "Distance",
      duration: "Duration",
      elevation: "Elevation",
      rating: "Rating",
      viewPhotos: "View all trip photos",
      paymentInfo: "Payment information",
      billingInfo: "Billing information",
      billingDate: "Billing date",
      myTrips: "My trips",
      viewMap: "View map",
      notifications: "Notifications",
      notificationsHelp: "Receive alerts for new messages and reservations",
      theme: "Theme",
      themeHelp: "Choose color and design preferences",
      chooseTheme: "Choose theme",
      lightTheme: "Light theme",
      darkTheme: "Dark theme",
      autoTheme: "Automatic",
      done: "Done",
      confirmLogout: "Are you sure?",
      place: "Location",
    },
  },
  fr: {
    footer: {
      text: "Fritt Fram. Planifiez des excursions, des cabanes et des expériences dans toute l'application.",
    },
    topBar: {
      search: "Recherche",
      explore: "Explorer",
      reserve: "Réserver",
      map: "Carte",
      weather: "Météo",
      social: "Social",
      navigate: "Naviguer",
      home: "Accueil",
      menu: "Menu",
      currentPage: "Page active",
      quickActions: "Accès rapides",
      language: "Langue",
      profile: "Profil",
      settings: "Paramètres",
      login: "Se connecter",
      logout: "Se déconnecter",
      guest: "Non connecté",
      signedInAs: "Connecté en tant que",
      account: "Compte",
      ads: "Marché",
      adPortal: "Portail Publicité",
    },
    home: {
      title: "Fritt Fram",
      subtitle: "Découvrez de nouveaux sentiers, respirez l'air de la montagne et trouvez votre prochaine aventure",
      searchPlaceholder: "Rechercher une excursion, un lieu ou une activité...",
      noResults: "Aucun résultat",
      todaysTrip: "Excursion du jour",
      popularRoutes: "Itinéraires populaires",
      cabinSuggestions: "Suggestions de cabanes",
      start: "Commencer",
      weather: "Météo",
      explore: "Explorer",
      map: "Carte",
      social: "Social",
      reserve: "Réserver",
      searchBtn: "Rechercher",
      showAllResults: "Voir tous les résultats",
      carouselEyebrow: "Populaire maintenant",
      carouselTitle: "Explorer le meilleur",
      tagLabels: { cabin: "Chalet", hike: "Randonnée", market: "Marché", rorbu: "Rorbu", bike: "Cyclisme", forum: "Communauté", weather: "Météo", climb: "Escalade" },
      cards: [
        { label: "Hébergement", title: "Chalet de montagne à Jotunheimen", desc: "Chalet rustique avec vue sur Besseggen. Capacité 8 personnes.", cta: "Réserver" },
        { label: "Activité", title: "Grande randonnée sur Hardangervidda", desc: "Itinéraire de 5 jours sur un des plus grands hauts plateaux d'Europe.", cta: "Voir l'itinéraire" },
        { label: "Équipement", title: "Chaussures de montagne tout terrain", desc: "Testées et approuvées par les randonneurs norvégiens. Au Marché.", cta: "Voir l'offre" },
        { label: "Hébergement", title: "Séjour côtier aux Lofoten", desc: "Rorbu au bord de la mer. Soleil, fruits de mer et soleil de minuit.", cta: "Réserver" },
        { label: "Activité", title: "Cyclisme sur Rallarvegen", desc: "82 km au-dessus de la montagne – la plus belle piste cyclable de Norvège.", cta: "Voir l'itinéraire" },
        { label: "Communauté", title: "Partagez votre prochain voyage", desc: "Trouvez des compagnons de randonnée et partagez vos expériences.", cta: "Aller au forum" },
        { label: "Météo", title: "Consultez la météo", desc: "Météo montagne actualisée pour plus de 500 sommets norvégiens.", cta: "Ouvrir la carte" },
        { label: "Activité", title: "Randonnées au sommet à Romsdalen", desc: "Itinéraires classiques avec vues spectaculaires. Tous niveaux.", cta: "Explorer" },
        { label: "Hébergement", title: "Chalet d'été au bord du lac", desc: "Calme, pagaie et pêche. Réservation ouverte pour l'été.", cta: "Réserver" },
      ],
    },
    searchPage: {
      eyebrow: "Recherche globale",
      title: "Trouver des excursions et des cabanes",
      subtitle: "Recherchez des excursions, des lieux et des cabanes. Les résultats mènent directement aux vues d'exploration et de réservation.",
      inputPlaceholder: "Rechercher une excursion ou une cabane",
      submit: "Rechercher",
      suggestions: "Suggestions",
      searchTerm: "Terme recherché",
      trips: "Excursions",
      cabins: "Cabanes",
      totalResults: "Résultats totaux",
      loading: "Recherche des excursions et des cabanes...",
      noHitsTitle: "Aucun résultat",
      noHitsDescription: "Essayez un autre terme de recherche ou allez directement aux pages d'exploration et de réservation.",
      noDescription: "Aucune description disponible.",
      openExplore: "Ouvrir dans explorer",
      openReserve: "Ouvrir dans réservation",
    },
    explorePage: {
      title: "Explorer la Norvège",
      subtitle: "Trouvez des excursions dans tout le pays",
      createTrip: "Créer une excursion",
      searchPlaceholder: "Rechercher des excursions",
      allTypes: "Tous les types",
      hike: "Randonnée",
      ski: "Ski",
      bike: "Vélo",
      difficulty: "Difficulté",
      easy: "Facile",
      medium: "Moyen",
      hard: "Difficile",
      tiuOnly: "Uniquement les sorties de groupe TiU",
      trips: "Excursions",
      noTrips: "Aucune excursion trouvée",
      createTitle: "Créer une nouvelle excursion",
      close: "Fermer",
      openDetails: "Voir les détails",
      name: "Nom",
      description: "Description",
      imageUrl: "URL de l'image",
      length: "Longueur (km)",
      type: "Type",
      difficultyLabel: "Difficulté",
      startLat: "Latitude départ",
      startLng: "Longitude départ",
      endLat: "Latitude arrivée",
      endLng: "Longitude arrivée",
      tiuToggle: "Il s'agit d'une sortie de groupe TiU",
      leader: "Guide",
      submit: "Enregistrer l'excursion",
      submitError: "Impossible de créer l'excursion",
      fetchError: "Impossible de récupérer les excursions",
      genericError: "Une erreur est survenue",
    },
    reservePage: {
      loadingCabins: "Chargement des cabanes...",
      availableCabins: "Cabanes disponibles : {count} trouvées",
      selectCabin: "Choisir une cabane",
      noCabins: "Aucune cabane dans la base de données pour le moment.",
      location: "Lieu",
      capacity: "Capacité",
      people: "personnes",
      pricePerNight: "par nuit",
      noAmenities: "Aucun équipement enregistré",
      reserveCabin: "Réserver cette cabane",
      addCabin: "Ajouter une nouvelle cabane",
      loading: "Chargement...",
      loadError: "Impossible de charger les données.",
      selectPrompt: "Choisissez une cabane dans la liste pour voir les détails.",
      cabinsLoadError: "Impossible de récupérer les cabanes depuis la base de données.",
      unknownCabinError: "Erreur inconnue lors du chargement des cabanes.",
    },
    newCabinPage: {
      notice: "Ajouter une nouvelle cabane",
      noticeDetail: "enregistrée dans la base de données",
      tips: "Conseils",
      facilityTip: "Équipements : écrivez-les séparés par des virgules",
      priceTip: "Le prix et la capacité doivent être numériques",
      locationTip: "Le lieu peut être par exemple : Hemsedal, Norvège",
      backOverview: "Retour à l'aperçu",
      newCabin: "Nouvelle cabane",
      pinRequired: "Vous devez placer une épingle sur la carte pour indiquer la position de la cabane.",
      saving: "Enregistrement...",
      saveCabin: "Enregistrer la cabane",
      savedCabin: "Cabane enregistrée : {name}",
      saveError: "Impossible d'enregistrer la cabane.",
      networkError: "Erreur réseau ou serveur.",
      namePlaceholder: "Nom (obligatoire)",
      descriptionPlaceholder: "Description (facultative)",
      locationPlaceholder: "Lieu (obligatoire)",
      pricePlaceholder: "Prix par nuit",
      capacityPlaceholder: "Capacité (nombre de personnes)",
      amenitiesPlaceholder: "Équipements (séparés par des virgules)",
      mapLabel: "Choisir un emplacement sur la carte",
      mapHelp: "Cliquez sur la carte pour placer une épingle. Les coordonnées sont enregistrées avec la cabane.",
      selectedPosition: "Position sélectionnée : {lat}, {lon}",
      overview: "Vers l'aperçu",
    },
    messagesPage: {
      title: "Messages",
      loading: "Chargement...",
      selectUser: "Choisissez un utilisateur avec qui discuter :",
      choose: "Choisir",
      loadingUsers: "Chargement des utilisateurs...",
      loadingMessages: "Chargement des messages...",
      noMessages: "Aucun message pour l'instant. Envoyez le premier.",
      inputPlaceholder: "Écrivez un message...",
      send: "Envoyer",
      currentUserError: "Impossible de récupérer l'utilisateur connecté",
      usersError: "Impossible de récupérer les utilisateurs",
      messagesError: "Impossible de récupérer les messages",
      sendError: "Impossible d'envoyer le message",
    },
    weatherPage: {
      title: "Recherche météo",
      inputPlaceholder: "Rechercher un lieu",
      submit: "Rechercher",
      now: "Maintenant",
      temperature: "Température",
      wind: "Vent",
      humidity: "Humidité",
      precipitation: "Précipitations (1h)",
      forecast: "Prévisions sur 7 jours",
      noResults: "Aucun lieu trouvé.",
    },
    mapPage: {
      title: "Carte de la Norvège",
    },
    utforskPage: {
      title: "Explorer",
      description: "Explorez ici des lieux et des expériences passionnantes.",
    },
    settingsPage: {
      title: "Paramètres",
      description: "Modifiez vos paramètres ici.",
    },
    loginPage: {
      eyebrow: "Connexion",
      title: "Reconnectez-vous",
      subtitle: "Après la déconnexion, vous devez vous reconnecter pour accéder au profil, aux messages et aux autres pages protégées.",
      checking: "Vérification de l'état de connexion...",
      email: "E-mail",
      password: "Mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      forgotPasswordHelp: "Saisissez votre e-mail et un nouveau mot de passe pour remplacer l'ancien dans la base de données.",
      newPassword: "Nouveau mot de passe",
      confirmNewPassword: "Confirmer le nouveau mot de passe",
      resetPassword: "Mettre à jour le mot de passe",
      resettingPassword: "Mise à jour du mot de passe...",
      resetSuccess: "Mot de passe mis à jour. L'ancien ne fonctionne plus.",
      resetError: "Impossible de mettre à jour le mot de passe",
      passwordMismatch: "Les mots de passe doivent correspondre",
      passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
      submitting: "Connexion en cours...",
      submit: "Se connecter",
      noAccount: "Vous n'avez pas de compte ?",
      signUp: "Créer un compte",
      loginError: "Impossible de se connecter",
    },
    signupPage: {
      title: "Créer un compte",
      username: "Nom d'utilisateur",
      email: "E-mail",
      password: "Mot de passe (minimum 8 caractères)",
      confirmPassword: "Confirmer le mot de passe",
      tourGuideSignupLabel: "Je m'inscris en tant que guide touristique",
      tourGuideSignupHint: "Vous serez enregistré avec le rôle Guide touristique.",
      landlordSignupLabel: "Je m'inscris en tant que loueur",
      landlordSignupHint: "Vous serez enregistré avec le rôle Loueur.",
      userSignupHint: "Si vous ne cochez pas cette case, vous serez enregistré en tant qu'utilisateur classique.",
      submitting: "Création du compte...",
      submit: "Créer un compte",
      signupError: "Impossible de créer le compte",
      genericError: "Une erreur est survenue",
    },
    socialPage: {
      title: "Social",
      captionPlaceholder: "Écrire une publication",
      publish: "Publier",
      likes: "mentions j'aime",
      currentUserError: "Impossible de récupérer l'utilisateur connecté",
      publishError: "Impossible de publier la publication",
      likeError: "Impossible de mettre à jour le statut j'aime",
      shareCopied: "Lien copié",
    },
    profilePage: {
      loading: "Chargement du profil depuis l'API...",
      account: "Mon compte",
      transactions: "Transactions",
      reservations: "Réservations",
      reservationsIntro: "Vous voyez ici les cabanes que vous avez réservées.",
      wishlist: "Liste de souhaits",
      wishlistIntro: "Vous voyez ici les cabanes enregistrées comme favorites.",
      loadingWishlist: "Chargement de la liste de souhaits...",
      noWishlistCabins: "Vous n'avez encore aucune cabane dans votre liste de souhaits.",
      removeFromWishlist: "Retirer de la liste",
      removingFromWishlist: "Suppression...",
      loadingReservations: "Chargement des réservations...",
      noReservations: "Vous n'avez encore aucune réservation enregistrée.",
      noCabinImage: "Aucune image",
      cabinFallback: "Cabane",
      locationUnavailable: "Lieu non disponible",
      pricePerNight: "Prix par nuit",
      capacity: "Capacité",
      people: "personnes",
      from: "Du",
      to: "Au",
      guests: "Personnes",
      openCabin: "Ouvrir la cabane",
      statusCancelled: "Annulée",
      statusConfirmed: "Confirmée",
      statusPending: "En attente",
      statusActive: "Active",
      payment: "Paiement",
      trips: "Excursions",
      settings: "Paramètres",
      logout: "Se déconnecter",
      categories: "Catégories",
      changeImage: "Changer l'image",
      editProfile: "Modifier le profil",
      name: "Nom",
      birthDate: "Date de naissance",
      age: "Âge",
      phone: "Téléphone",
      email: "E-mail",
      bio: "Bio",
      save: "Enregistrer",
      cancel: "Annuler",
      details: "Détails",
      date: "Date",
      distance: "Distance",
      duration: "Durée",
      elevation: "Dénivelé",
      rating: "Évaluation",
      viewPhotos: "Voir toutes les photos de l'excursion",
      paymentInfo: "Informations de paiement",
      billingInfo: "Informations de facturation",
      billingDate: "Date de facturation",
      myTrips: "Mes excursions",
      viewMap: "Voir la carte",
      notifications: "Notifications",
      notificationsHelp: "Recevoir des alertes pour les nouveaux messages et réservations",
      theme: "Thème",
      themeHelp: "Choisissez les préférences de couleur et de design",
      chooseTheme: "Choisir un thème",
      lightTheme: "Thème clair",
      darkTheme: "Thème sombre",
      autoTheme: "Automatique",
      done: "Terminé",
      confirmLogout: "Êtes-vous sûr ?",
      place: "Lieu",
    },
  },
  es: {
    footer: {
      text: "Fritt Fram. Planifica excursiones, cabañas y experiencias en toda la aplicación.",
    },
    topBar: {
      search: "Buscar",
      explore: "Explorar",
      reserve: "Reservar",
      map: "Mapa",
      weather: "Clima",
      social: "Social",
      navigate: "Navegar",
      home: "Inicio",
      menu: "Menú",
      currentPage: "Página activa",
      quickActions: "Accesos rápidos",
      language: "Idioma",
      profile: "Perfil",
      settings: "Configuración",
      login: "Iniciar sesión",
      logout: "Cerrar sesión",
      guest: "No has iniciado sesión",
      signedInAs: "Sesión iniciada como",
      account: "Cuenta",
      ads: "Mercado",
      adPortal: "Portal de Anuncios",
    },
    home: {
      title: "Fritt Fram",
      subtitle: "Descubre nuevos senderos, respira el aire de la montaña y encuentra tu próxima aventura",
      searchPlaceholder: "Buscar excursión, lugar o actividad...",
      noResults: "Sin resultados",
      todaysTrip: "Excursión del día",
      popularRoutes: "Rutas populares",
      cabinSuggestions: "Sugerencias de cabañas",
      start: "Comenzar",
      weather: "Clima",
      explore: "Explorar",
      map: "Mapa",
      social: "Social",
      reserve: "Reservar",
      searchBtn: "Buscar",
      showAllResults: "Ver todos los resultados",
      carouselEyebrow: "Popular ahora",
      carouselTitle: "Explora lo mejor",
      tagLabels: { cabin: "Cabaña", hike: "Senderismo", market: "Mercado", rorbu: "Rorbu", bike: "Ciclismo", forum: "Comunidad", weather: "Clima", climb: "Escalada" },
      cards: [
        { label: "Alojamiento", title: "Cabaña de montaña en Jotunheimen", desc: "Cabaña rústica con vistas a Besseggen. Para 8 personas.", cta: "Reservar" },
        { label: "Actividad", title: "Gran caminata en Hardangervidda", desc: "Ruta de 5 días por uno de los mayores altiplanos de Europa.", cta: "Ver ruta" },
        { label: "Equipo", title: "Botas de montaña para todo terreno", desc: "Probadas y aprobadas por excursionistas noruegos. En el Mercado.", cta: "Ver oferta" },
        { label: "Alojamiento", title: "Escapada costera en Lofoten", desc: "Rorbu junto al mar. Sol, marisco y sol de medianoche.", cta: "Reservar" },
        { label: "Actividad", title: "Ciclismo por Rallarvegen", desc: "82 km sobre la montaña – la mejor ruta ciclista de Noruega.", cta: "Ver ruta" },
        { label: "Comunidad", title: "Comparte tu próxima excursión", desc: "Encuentra compañeros de senderismo y comparte experiencias.", cta: "Ir al foro" },
        { label: "Clima", title: "Consulta el pronóstico", desc: "Clima de montaña actualizado para más de 500 cumbres noruegas.", cta: "Abrir mapa" },
        { label: "Actividad", title: "Ascensiones en Romsdalen", desc: "Rutas clásicas con vistas espectaculares. Todos los niveles.", cta: "Explorar" },
        { label: "Alojamiento", title: "Cabaña de verano junto al lago", desc: "Tranquilidad, piragüismo y pesca. Reservas abiertas para el verano.", cta: "Reservar" },
      ],
    },
    searchPage: {
      eyebrow: "Búsqueda global",
      title: "Encontrar excursiones y cabañas",
      subtitle: "Busca excursiones, lugares y cabañas. Los resultados te llevan directamente a las vistas de exploración y reservas.",
      inputPlaceholder: "Buscar excursión o cabaña",
      submit: "Buscar",
      suggestions: "Sugerencias",
      searchTerm: "Término de búsqueda",
      trips: "Excursiones",
      cabins: "Cabañas",
      totalResults: "Resultados totales",
      loading: "Buscando excursiones y cabañas...",
      noHitsTitle: "Sin resultados",
      noHitsDescription: "Prueba con otro término de búsqueda o ve directamente a las páginas de exploración y reservas.",
      noDescription: "No hay descripción disponible.",
      openExplore: "Abrir en explorar",
      openReserve: "Abrir en reservas",
    },
    explorePage: {
      title: "Explorar Noruega",
      subtitle: "Encuentra excursiones en todo el país",
      createTrip: "Crear excursión",
      searchPlaceholder: "Buscar excursiones",
      allTypes: "Todos los tipos",
      hike: "Senderismo",
      ski: "Esquí",
      bike: "Bicicleta",
      difficulty: "Dificultad",
      easy: "Fácil",
      medium: "Media",
      hard: "Difícil",
      tiuOnly: "Solo excursiones grupales de TiU",
      trips: "Excursiones",
      noTrips: "No se encontraron excursiones",
      createTitle: "Crear nueva excursión",
      close: "Cerrar",
      openDetails: "Ver detalles",
      name: "Nombre",
      description: "Descripción",
      imageUrl: "URL de la imagen",
      length: "Longitud (km)",
      type: "Tipo",
      difficultyLabel: "Dificultad",
      startLat: "Latitud inicial",
      startLng: "Longitud inicial",
      endLat: "Latitud final",
      endLng: "Longitud final",
      tiuToggle: "Esta es una excursión grupal de TiU",
      leader: "Guía",
      submit: "Guardar excursión",
      submitError: "No se pudo crear la excursión",
      fetchError: "No se pudieron obtener las excursiones",
      genericError: "Algo salió mal",
    },
    reservePage: {
      loadingCabins: "Cargando cabañas...",
      availableCabins: "Cabañas disponibles: {count} encontradas",
      selectCabin: "Elegir una cabaña",
      noCabins: "Todavía no hay cabañas en la base de datos.",
      location: "Ubicación",
      capacity: "Capacidad",
      people: "personas",
      pricePerNight: "por noche",
      noAmenities: "No hay servicios registrados",
      reserveCabin: "Reservar esta cabaña",
      addCabin: "Añadir nueva cabaña",
      loading: "Cargando...",
      loadError: "No se pudieron cargar los datos.",
      selectPrompt: "Elige una cabaña de la lista para ver los detalles.",
      cabinsLoadError: "No se pudieron obtener las cabañas desde la base de datos.",
      unknownCabinError: "Error desconocido al cargar las cabañas.",
    },
    newCabinPage: {
      notice: "Añadir nueva cabaña",
      noticeDetail: "guardada en la base de datos",
      tips: "Consejos",
      facilityTip: "Servicios: escríbelos separados por comas",
      priceTip: "El precio y la capacidad deben ser números",
      locationTip: "La ubicación puede ser, por ejemplo: Hemsedal, Noruega",
      backOverview: "Volver al resumen",
      newCabin: "Nueva cabaña",
      pinRequired: "Debes colocar un marcador en el mapa para la ubicación de la cabaña.",
      saving: "Guardando...",
      saveCabin: "Guardar cabaña",
      savedCabin: "Cabaña guardada: {name}",
      saveError: "No se pudo guardar la cabaña.",
      networkError: "Error de red o del servidor.",
      namePlaceholder: "Nombre (obligatorio)",
      descriptionPlaceholder: "Descripción (opcional)",
      locationPlaceholder: "Ubicación (obligatoria)",
      pricePlaceholder: "Precio por noche",
      capacityPlaceholder: "Capacidad (número de personas)",
      amenitiesPlaceholder: "Servicios (separados por comas)",
      mapLabel: "Elegir una ubicación en el mapa",
      mapHelp: "Haz clic en el mapa para colocar un marcador. Las coordenadas se guardan con la cabaña.",
      selectedPosition: "Posición seleccionada: {lat}, {lon}",
      overview: "Al resumen",
    },
    messagesPage: {
      title: "Mensajes",
      loading: "Cargando...",
      selectUser: "Elige un usuario con quien chatear:",
      choose: "Elegir",
      loadingUsers: "Cargando usuarios...",
      loadingMessages: "Cargando mensajes...",
      noMessages: "Aún no hay mensajes. Envía el primero.",
      inputPlaceholder: "Escribe un mensaje...",
      send: "Enviar",
      currentUserError: "No se pudo obtener el usuario conectado",
      usersError: "No se pudieron obtener los usuarios",
      messagesError: "No se pudieron obtener los mensajes",
      sendError: "No se pudo enviar el mensaje",
    },
    weatherPage: {
      title: "Búsqueda del tiempo",
      inputPlaceholder: "Buscar un lugar",
      submit: "Buscar",
      now: "Ahora",
      temperature: "Temperatura",
      wind: "Viento",
      humidity: "Humedad",
      precipitation: "Precipitación (1h)",
      forecast: "Pronóstico de 7 días",
      noResults: "No se encontraron lugares.",
    },
    mapPage: {
      title: "Mapa de Noruega",
    },
    utforskPage: {
      title: "Explorar",
      description: "Explora lugares y experiencias aquí.",
    },
    settingsPage: {
      title: "Configuración",
      description: "Cambia tu configuración aquí.",
    },
    loginPage: {
      eyebrow: "Inicio de sesión",
      title: "Vuelve a iniciar sesión",
      subtitle: "Después de cerrar sesión, debes volver a iniciar sesión para acceder al perfil, los mensajes y otras páginas protegidas.",
      checking: "Comprobando el estado de inicio de sesión...",
      email: "Correo electrónico",
      password: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      forgotPasswordHelp: "Escribe tu correo y una nueva contraseña para sobrescribir la antigua en la base de datos.",
      newPassword: "Nueva contraseña",
      confirmNewPassword: "Confirmar nueva contraseña",
      resetPassword: "Actualizar contraseña",
      resettingPassword: "Actualizando contraseña...",
      resetSuccess: "Contraseña actualizada. La contraseña anterior ya no funciona.",
      resetError: "No se pudo actualizar la contraseña",
      passwordMismatch: "Las contraseñas deben coincidir",
      passwordTooShort: "La contraseña debe tener al menos 8 caracteres",
      submitting: "Iniciando sesión...",
      submit: "Iniciar sesión",
      noAccount: "¿No tienes cuenta?",
      signUp: "Crear una",
      loginError: "No se pudo iniciar sesión",
    },
    signupPage: {
      title: "Crear cuenta",
      username: "Nombre de usuario",
      email: "Correo electrónico",
      password: "Contraseña (mínimo 8 caracteres)",
      confirmPassword: "Confirmar contraseña",
      tourGuideSignupLabel: "Me registro como guía turístico",
      tourGuideSignupHint: "Se te registrará con el rol de Guía turístico.",
      landlordSignupLabel: "Me registro como arrendador",
      landlordSignupHint: "Se te registrará con el rol de Arrendador.",
      userSignupHint: "Si no marcas esta opción, se te registrará como usuario normal.",
      submitting: "Creando cuenta...",
      submit: "Crear cuenta",
      signupError: "No se pudo crear la cuenta",
      genericError: "Algo salió mal",
    },
    socialPage: {
      title: "Social",
      captionPlaceholder: "Escribir una publicación",
      publish: "Publicar",
      likes: "me gusta",
      currentUserError: "No se pudo obtener el usuario conectado",
      publishError: "No se pudo publicar la publicación",
      likeError: "No se pudo actualizar el estado de me gusta",
      shareCopied: "Enlace copiado",
    },
    profilePage: {
      loading: "Cargando perfil desde la API...",
      account: "Mi cuenta",
      transactions: "Transacciones",
      reservations: "Reservas",
      reservationsIntro: "Aquí puedes ver las cabañas que has reservado.",
      wishlist: "Lista de deseos",
      wishlistIntro: "Aquí puedes ver las cabañas guardadas como favoritas.",
      loadingWishlist: "Cargando lista de deseos...",
      noWishlistCabins: "Todavía no tienes cabañas en tu lista de deseos.",
      removeFromWishlist: "Quitar de la lista",
      removingFromWishlist: "Quitando...",
      loadingReservations: "Cargando reservas...",
      noReservations: "Todavía no tienes reservas registradas.",
      noCabinImage: "Sin imagen",
      cabinFallback: "Cabaña",
      locationUnavailable: "Ubicación no disponible",
      pricePerNight: "Precio por noche",
      capacity: "Capacidad",
      people: "personas",
      from: "Desde",
      to: "Hasta",
      guests: "Personas",
      openCabin: "Abrir cabaña",
      statusCancelled: "Cancelada",
      statusConfirmed: "Confirmada",
      statusPending: "Pendiente",
      statusActive: "Activa",
      payment: "Pago",
      trips: "Excursiones",
      settings: "Configuración",
      logout: "Cerrar sesión",
      categories: "Categorías",
      changeImage: "Cambiar imagen",
      editProfile: "Editar perfil",
      name: "Nombre",
      birthDate: "Fecha de nacimiento",
      age: "Edad",
      phone: "Teléfono",
      email: "Correo electrónico",
      bio: "Bio",
      save: "Guardar",
      cancel: "Cancelar",
      details: "Detalles",
      date: "Fecha",
      distance: "Distancia",
      duration: "Duración",
      elevation: "Desnivel",
      rating: "Valoración",
      viewPhotos: "Ver todas las fotos de la excursión",
      paymentInfo: "Información de pago",
      billingInfo: "Información de facturación",
      billingDate: "Fecha de facturación",
      myTrips: "Mis excursiones",
      viewMap: "Ver mapa",
      notifications: "Notificaciones",
      notificationsHelp: "Recibe alertas sobre nuevos mensajes y reservas",
      theme: "Tema",
      themeHelp: "Elige preferencias de color y diseño",
      chooseTheme: "Elegir tema",
      lightTheme: "Tema claro",
      darkTheme: "Tema oscuro",
      autoTheme: "Automático",
      done: "Listo",
      confirmLogout: "¿Estás seguro?",
      place: "Ubicación",
    },
  },
  it: {
    footer: {
      text: "Fritt Fram. Pianifica escursioni, cabine ed esperienze in tutta l'applicazione.",
    },
    topBar: {
      search: "Cerca",
      explore: "Esplora",
      reserve: "Prenota",
      map: "Mappa",
      weather: "Meteo",
      social: "Social",
      navigate: "Naviga",
      home: "Home",
      menu: "Menu",
      currentPage: "Pagina attiva",
      quickActions: "Azioni rapide",
      language: "Lingua",
      profile: "Profilo",
      settings: "Impostazioni",
      login: "Accedi",
      logout: "Esci",
      guest: "Non hai effettuato l'accesso",
      signedInAs: "Accesso come",
      account: "Account",
      ads: "Mercato",
      adPortal: "Portale Annunci",
    },
    home: {
      title: "Fritt Fram",
      subtitle: "Scopri nuovi sentieri, respira l'aria di montagna e trova la tua prossima avventura",
      searchPlaceholder: "Cerca un'escursione, un luogo o un'attività...",
      noResults: "Nessun risultato",
      todaysTrip: "Escursione del giorno",
      popularRoutes: "Percorsi popolari",
      cabinSuggestions: "Suggerimenti per cabine",
      start: "Inizia",
      weather: "Meteo",
      explore: "Esplora",
      map: "Mappa",
      social: "Social",
      reserve: "Prenota",
      searchBtn: "Cerca",
      showAllResults: "Mostra tutti i risultati",
      carouselEyebrow: "Popolare ora",
      carouselTitle: "Esplora il meglio",
      tagLabels: { cabin: "Chalet", hike: "Escursione", market: "Mercato", rorbu: "Rorbu", bike: "Ciclismo", forum: "Comunità", weather: "Meteo", climb: "Arrampicata" },
      cards: [
        { label: "Alloggio", title: "Chalet di montagna a Jotunheimen", desc: "Chalet rustico con vista su Besseggen. Per 8 persone.", cta: "Prenota" },
        { label: "Attività", title: "Lunga escursione sull'Hardangervidda", desc: "Percorso di 5 giorni su uno dei maggiori altipiani d'Europa.", cta: "Vedi percorso" },
        { label: "Attrezzatura", title: "Stivali da montagna per tutti i terreni", desc: "Testati e approvati dagli escursionisti norvegesi. Al Mercato.", cta: "Vedi offerta" },
        { label: "Alloggio", title: "Soggiorno costiero alle Lofoten", desc: "Rorbu sul mare. Sole, frutti di mare e sole di mezzanotte.", cta: "Prenota" },
        { label: "Attività", title: "Ciclismo lungo Rallarvegen", desc: "82 km sopra la montagna – la più bella pista ciclabile della Norvegia.", cta: "Vedi percorso" },
        { label: "Comunità", title: "Condividi il tuo prossimo viaggio", desc: "Trova compagni di escursioni e condividi esperienze nel forum.", cta: "Vai al forum" },
        { label: "Meteo", title: "Controlla le previsioni", desc: "Meteo montagna aggiornato per oltre 500 vette norvegesi.", cta: "Apri mappa" },
        { label: "Attività", title: "Escursioni in vetta a Romsdalen", desc: "Percorsi classici con viste spettacolari. Tutti i livelli.", cta: "Esplora" },
        { label: "Alloggio", title: "Chalet estivo sul lago", desc: "Tranquillità, canoa e pesca. Prenotazione aperta per l'estate.", cta: "Prenota" },
      ],
    },
    searchPage: {
      eyebrow: "Ricerca globale",
      title: "Trova escursioni e cabine",
      subtitle: "Cerca escursioni, luoghi e cabine. I risultati portano direttamente alle viste di esplorazione e prenotazione.",
      inputPlaceholder: "Cerca un'escursione o una cabina",
      submit: "Cerca",
      suggestions: "Suggerimenti",
      searchTerm: "Termine di ricerca",
      trips: "Escursioni",
      cabins: "Cabine",
      totalResults: "Risultati totali",
      loading: "Ricerca di escursioni e cabine in corso...",
      noHitsTitle: "Nessun risultato",
      noHitsDescription: "Prova un altro termine di ricerca oppure vai direttamente alle pagine di esplorazione e prenotazione.",
      noDescription: "Nessuna descrizione disponibile.",
      openExplore: "Apri in esplora",
      openReserve: "Apri in prenotazioni",
    },
    explorePage: {
      title: "Esplora la Norvegia",
      subtitle: "Trova escursioni in tutto il paese",
      createTrip: "Crea escursione",
      searchPlaceholder: "Cerca escursioni",
      allTypes: "Tutti i tipi",
      hike: "Escursionismo",
      ski: "Sci",
      bike: "Bici",
      difficulty: "Difficoltà",
      easy: "Facile",
      medium: "Media",
      hard: "Difficile",
      tiuOnly: "Solo escursioni di gruppo TiU",
      trips: "Escursioni",
      noTrips: "Nessuna escursione trovata",
      createTitle: "Crea una nuova escursione",
      close: "Chiudi",
      openDetails: "Vedi dettagli",
      name: "Nome",
      description: "Descrizione",
      imageUrl: "URL immagine",
      length: "Lunghezza (km)",
      type: "Tipo",
      difficultyLabel: "Difficoltà",
      startLat: "Latitudine iniziale",
      startLng: "Longitudine iniziale",
      endLat: "Latitudine finale",
      endLng: "Longitudine finale",
      tiuToggle: "Questa è un'escursione di gruppo TiU",
      leader: "Guida",
      submit: "Salva escursione",
      submitError: "Impossibile creare l'escursione",
      fetchError: "Impossibile recuperare le escursioni",
      genericError: "Si è verificato un errore",
    },
    reservePage: {
      loadingCabins: "Caricamento delle cabine...",
      availableCabins: "Cabine disponibili: {count} trovate",
      selectCabin: "Scegli una cabina",
      noCabins: "Non ci sono ancora cabine nel database.",
      location: "Luogo",
      capacity: "Capacità",
      people: "persone",
      pricePerNight: "a notte",
      noAmenities: "Nessun servizio registrato",
      reserveCabin: "Prenota questa cabina",
      addCabin: "Aggiungi una nuova cabina",
      loading: "Caricamento...",
      loadError: "Impossibile caricare i dati.",
      selectPrompt: "Scegli una cabina dalla lista per vedere i dettagli.",
      cabinsLoadError: "Impossibile recuperare le cabine dal database.",
      unknownCabinError: "Errore sconosciuto durante il caricamento delle cabine.",
    },
    newCabinPage: {
      notice: "Aggiungi una nuova cabina",
      noticeDetail: "salvata nel database",
      tips: "Suggerimenti",
      facilityTip: "Servizi: scrivili separati da virgole",
      priceTip: "Prezzo e capacità devono essere numeri",
      locationTip: "La posizione può essere ad esempio: Hemsedal, Norvegia",
      backOverview: "Torna alla panoramica",
      newCabin: "Nuova cabina",
      pinRequired: "Devi posizionare un segnaposto sulla mappa per la posizione della cabina.",
      saving: "Salvataggio...",
      saveCabin: "Salva cabina",
      savedCabin: "Cabina salvata: {name}",
      saveError: "Impossibile salvare la cabina.",
      networkError: "Errore di rete o del server.",
      namePlaceholder: "Nome (obbligatorio)",
      descriptionPlaceholder: "Descrizione (facoltativa)",
      locationPlaceholder: "Luogo (obbligatorio)",
      pricePlaceholder: "Prezzo per notte",
      capacityPlaceholder: "Capacità (numero di persone)",
      amenitiesPlaceholder: "Servizi (separati da virgole)",
      mapLabel: "Scegli una posizione sulla mappa",
      mapHelp: "Fai clic sulla mappa per posizionare un segnaposto. Le coordinate vengono salvate con la cabina.",
      selectedPosition: "Posizione selezionata: {lat}, {lon}",
      overview: "Alla panoramica",
    },
    messagesPage: {
      title: "Messaggi",
      loading: "Caricamento...",
      selectUser: "Scegli un utente con cui chattare:",
      choose: "Scegli",
      loadingUsers: "Caricamento utenti...",
      loadingMessages: "Caricamento messaggi...",
      noMessages: "Ancora nessun messaggio. Invia il primo.",
      inputPlaceholder: "Scrivi un messaggio...",
      send: "Invia",
      currentUserError: "Impossibile recuperare l'utente connesso",
      usersError: "Impossibile recuperare gli utenti",
      messagesError: "Impossibile recuperare i messaggi",
      sendError: "Impossibile inviare il messaggio",
    },
    weatherPage: {
      title: "Ricerca meteo",
      inputPlaceholder: "Cerca un luogo",
      submit: "Cerca",
      now: "Ora",
      temperature: "Temperatura",
      wind: "Vento",
      humidity: "Umidità",
      precipitation: "Precipitazioni (1h)",
      forecast: "Previsioni di 7 giorni",
      noResults: "Nessun luogo trovato.",
    },
    mapPage: {
      title: "Mappa della Norvegia",
    },
    utforskPage: {
      title: "Esplora",
      description: "Esplora luoghi ed esperienze qui.",
    },
    settingsPage: {
      title: "Impostazioni",
      description: "Modifica qui le tue impostazioni.",
    },
    loginPage: {
      eyebrow: "Accesso",
      title: "Accedi di nuovo",
      subtitle: "Dopo la disconnessione, devi accedere di nuovo per aprire profilo, messaggi e altre pagine protette.",
      checking: "Verifica dello stato di accesso...",
      email: "E-mail",
      password: "Password",
      forgotPassword: "Password dimenticata?",
      forgotPasswordHelp: "Inserisci e-mail e nuova password per sovrascrivere quella vecchia nel database.",
      newPassword: "Nuova password",
      confirmNewPassword: "Conferma nuova password",
      resetPassword: "Aggiorna password",
      resettingPassword: "Aggiornamento password...",
      resetSuccess: "Password aggiornata. Quella vecchia non funziona più.",
      resetError: "Impossibile aggiornare la password",
      passwordMismatch: "Le password devono corrispondere",
      passwordTooShort: "La password deve contenere almeno 8 caratteri",
      submitting: "Accesso in corso...",
      submit: "Accedi",
      noAccount: "Non hai un account?",
      signUp: "Creane uno",
      loginError: "Impossibile accedere",
    },
    signupPage: {
      title: "Crea account",
      username: "Nome utente",
      email: "E-mail",
      tourGuideSignupLabel: "Mi registro come guida turistica",
      tourGuideSignupHint: "Verrai registrato con il ruolo di Guida turistica.",
      password: "Password (minimo 8 caratteri)",
      confirmPassword: "Conferma password",
      landlordSignupLabel: "Mi registro come locatore",
      landlordSignupHint: "Verrai registrato con il ruolo di Locatore.",
      userSignupHint: "Se non selezioni questa opzione, verrai registrato come utente normale.",
      submitting: "Creazione account in corso...",
      submit: "Crea account",
      signupError: "Impossibile creare l'account",
      genericError: "Si è verificato un errore",
    },
    socialPage: {
      title: "Social",
      captionPlaceholder: "Scrivi un post",
      publish: "Pubblica",
      likes: "mi piace",
      currentUserError: "Impossibile recuperare l'utente connesso",
      publishError: "Impossibile pubblicare il post",
      likeError: "Impossibile aggiornare lo stato del like",
      shareCopied: "Link copiato",
    },
    profilePage: {
      loading: "Caricamento del profilo dall'API...",
      account: "Il mio account",
      transactions: "Transazioni",
      reservations: "Prenotazioni",
      reservationsIntro: "Qui puoi vedere le cabine che hai prenotato.",
      wishlist: "Lista dei desideri",
      wishlistIntro: "Qui puoi vedere le cabine salvate come preferite.",
      loadingWishlist: "Caricamento lista dei desideri...",
      noWishlistCabins: "Non hai ancora cabine nella lista dei desideri.",
      removeFromWishlist: "Rimuovi dalla lista",
      removingFromWishlist: "Rimozione...",
      loadingReservations: "Caricamento prenotazioni...",
      noReservations: "Non hai ancora prenotazioni registrate.",
      noCabinImage: "Nessuna immagine",
      cabinFallback: "Cabina",
      locationUnavailable: "Luogo non disponibile",
      pricePerNight: "Prezzo per notte",
      capacity: "Capacità",
      people: "persone",
      from: "Da",
      to: "A",
      guests: "Persone",
      openCabin: "Apri cabina",
      statusCancelled: "Annullata",
      statusConfirmed: "Confermata",
      statusPending: "In attesa",
      statusActive: "Attiva",
      payment: "Pagamento",
      trips: "Escursioni",
      settings: "Impostazioni",
      logout: "Esci",
      categories: "Categorie",
      changeImage: "Cambia immagine",
      editProfile: "Modifica profilo",
      name: "Nome",
      birthDate: "Data di nascita",
      age: "Età",
      phone: "Telefono",
      email: "E-mail",
      bio: "Bio",
      save: "Salva",
      cancel: "Annulla",
      details: "Dettagli",
      date: "Data",
      distance: "Distanza",
      duration: "Durata",
      elevation: "Dislivello",
      rating: "Valutazione",
      viewPhotos: "Vedi tutte le foto dell'escursione",
      paymentInfo: "Informazioni di pagamento",
      billingInfo: "Informazioni di fatturazione",
      billingDate: "Data di fatturazione",
      myTrips: "Le mie escursioni",
      viewMap: "Vedi mappa",
      notifications: "Notifiche",
      notificationsHelp: "Ricevi avvisi per nuovi messaggi e prenotazioni",
      theme: "Tema",
      themeHelp: "Scegli preferenze di colore e design",
      chooseTheme: "Scegli tema",
      lightTheme: "Tema chiaro",
      darkTheme: "Tema scuro",
      autoTheme: "Automatico",
      done: "Fatto",
      confirmLogout: "Sei sicuro?",
      place: "Luogo",
    },
  },
};

const LanguageContext = createContext(null);

function getDictionary(language, namespace) {
  const safeLanguage = LANGUAGE_OPTIONS.includes(language) ? language : "no";
  const fallbackNamespace = dictionaries.en?.[namespace] || {};
  const defaultNamespace = dictionaries.no?.[namespace] || {};
  const languageNamespace = dictionaries[safeLanguage]?.[namespace] || {};

  return {
    ...fallbackNamespace,
    ...defaultNamespace,
    ...languageNamespace,
  };
}

function interpolate(template, values) {
  if (typeof template !== "string") {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (_, key) => `${values?.[key] ?? ""}`);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("no");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let cancelled = false;

    async function loadPreferences() {
      try {
        const res = await fetch("/api/preferences", { cache: "no-store" });
        const json = await res.json().catch(() => ({}));

        if (!cancelled && res.ok && LANGUAGE_OPTIONS.includes(json?.language)) {
          setLanguage(json.language);
        }
      } finally {
        if (!cancelled) {
          setReady(true);
        }
      }
    }

    loadPreferences();

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    if (!ready) {
      return;
    }

    fetch("/api/preferences", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ language }),
    }).catch(() => {});
  }, [language, ready]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      ready,
      languages: LANGUAGE_OPTIONS,
    }),
    [language, ready]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}

export function useTranslations(namespace) {
  const { language } = useLanguage();

  return useMemo(() => {
    const dictionary = getDictionary(language, namespace);

    return new Proxy(dictionary, {
      get(target, prop) {
        return target[prop] ?? prop;
      },
    });
  }, [language, namespace]);
}

export function translateLabel(language, namespace, key, values) {
  return interpolate(getDictionary(language, namespace)?.[key] ?? key, values);
}

export function formatTranslation(template, values) {
  return interpolate(template, values);
}