import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="no">
      <body style={{ margin: 0, padding: 0 }}>
        <TopBar />

        {children}

        <footer className="footer">
          Dette er en footer som ligger over bildene
        </footer>
      </body>
    </html>
  );
}
