import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShell from "./components/AppShell";
import { LanguageProvider } from "./components/LanguageProvider";
import CookieBanner from "./components/CookieBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="no">
      <body style={{ margin: 0, padding: 0 }}>
        <div className="school-project-banner">
          DETTE ER ET SKOLEPROSJEKT
        </div>
        <LanguageProvider>
          <AppShell>{children}</AppShell>
          <CookieBanner />
        </LanguageProvider>
      </body>
    </html>
  );
}
